### Get repositories
GET http://localhost:3001/repositories

### Create a new Organization
POST http://localhost:3001/organizations
Content-Type: application/json

{

    "name": "org1",
    "status": 1
}

### Get the list of all organizations
GET http://localhost:3001/organizations

### Patch an organization by a given id
PATCH http://localhost:3001/organizations/1
Content-Type: application/json

{
    "name": "British Airways"
}

### Delete an organization by a given id
DELETE http://localhost:3001/organizations/14


### Creates a new Tribe
POST http://localhost:3001/tribes/1
Content-Type: application/json

{
    "name": "tribe 1",
    "status": 1
}

### Creates a new Repository
POST http://localhost:3001/repositories/1
Content-Type: application/json

{
    "name": "repo 7",
    "state": "E",
    "createTime": "2018-11-12 01:02:03.123456789",
    "status": "A"
}

### Get Tribe repos

GET http://localhost:3001/tribes/repositories/1

### Get Tribe

GET http://localhost:3001/tribes/2

### Creates a new Metric
POST http://localhost:3001/metrics/6
Content-Type: application/json

{
    "coverage": 13213,
    "bugs": 56,
    "vulnerabilities": 356563,
    "hotspot":561,
    "codeSmells": 26556
}